version: 1
disable_existing_loggers: true

formatters:
  simple:
    format: "%(asctime)s:%(levelname)8s:%(name)12s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: $level
    formatter: simple
    stream: ext://sys.stdout

loggers:
  ws:
    level: $level
    handlers: [console]
    propagate: no

root:
  level: $level
  handlers: [console]
